import tkinter as tk
from tkinter import ttk
def add_student():
    name = name_entry.get()
    age = age_entry.get()
    grade = grade_var.get()
    tree.insert("", tk.END, values=(name, age, grade))
    name_entry.delete(0, tk.END)
    age_entry.delete(0, tk.END)
    grade_var.set("A")
def delete_Selected():
    selected = tree.selection()
    if selected:
        tree.delete(selected)
window = tk.Tk()
window.title("Student manager ")
frame = tk.Frame(window, padx=20, pady=20)
frame.pack()
label = tk.Label(frame, text="Name")
label.grid(column=0, row=0)
name_entry = tk.Entry(frame)
name_entry.grid(row=0, column=1)
age_label = tk.Label(frame , text="Age")
age_label.grid(row= 1, column=0)
age_entry = tk.Entry(frame)
age_entry.grid(row=1, column=1)
grade_var = tk.StringVar()
grade_var.set("A")
grade_menu = tk.OptionMenu(frame, grade_var, "A", "B", "C", "D")
grade_menu.grid(row=2, column=1)
button = tk.Button(frame , text="Add Student", command=add_student)
button.grid(row = 3, column=0, columnspan=2)
tree = ttk.Treeview(window, columns=("Name", "Age", "Grade"), show="headings")
tree.heading("Name", text="Name")
tree.heading("Age", text="Age")
tree.heading("Grade", text="Grade")
tree.pack()
delete_button = tk.Button(window, text="Delete Selected", command=delete_Selected)
delete_button.pack()
window.mainloop()